import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import {
  ArrowLeftIcon,
  BriefcaseIcon,
  GlobeIcon,
  GraduationCapIcon,
  LinkIcon,
  MailIcon,
  MapPinIcon,
  MessageCircleIcon,
  PencilIcon,
  DropletIcon,
  UserIcon,
  UsersIcon,
} from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { countryName } from "@/lib/countries";
import { bloodGroupLabel } from "@/lib/blood-group";
import { genderLabel } from "@/lib/gender";
import { getProfileBySlug, type PublicProfile } from "@/lib/dal/profiles";
import { getViewer } from "@/lib/dal/session";
import { initialsOf } from "@/lib/utils";

/**
 * Next 16 passes `params` as a Promise. `PageProps` is generated by `next typegen`, but the
 * explicit shape here keeps the file readable without running codegen first.
 */
type ProfilePageProps = { params: Promise<{ slug: string }> };

export async function generateMetadata({ params }: ProfilePageProps): Promise<Metadata> {
  const { slug } = await params;
  const profile = await getProfileBySlug(slug);

  if (!profile) return { title: "Profile not found", robots: { index: false } };

  return {
    title: profile.displayName,
    description: profile.headline ?? undefined,
    // Even PUBLIC profiles stay out of search indexes; "public" here means visible to
    // signed-out visitors who have the link, not crawlable.
    robots: { index: false, follow: false },
  };
}

export default async function ProfilePage({ params }: ProfilePageProps) {
  const { slug } = await params;
  const [profile, viewer] = await Promise.all([getProfileBySlug(slug), getViewer()]);

  // The DAL returns null both for "does not exist" and "not visible to you". Presenting
  // both as 404 avoids confirming that a hidden profile exists.
  if (!profile) notFound();

  const location = [profile.city, profile.countryCode ? countryName(profile.countryCode) : null]
    .filter(Boolean)
    .join(", ");
  const role = [profile.position, profile.company].filter(Boolean).join(" at ");

  const facts = [
    profile.graduationYear
      ? { icon: GraduationCapIcon, label: `School · SSC ${profile.graduationYear}` }
      : null,
    profile.departmentName ? { icon: GraduationCapIcon, label: profile.departmentName } : null,
    role ? { icon: BriefcaseIcon, label: role } : null,
    location ? { icon: MapPinIcon, label: location } : null,
    profile.gender ? { icon: UserIcon, label: genderLabel(profile.gender) } : null,
    profile.bloodGroup
      ? { icon: DropletIcon, label: bloodGroupLabel(profile.bloodGroup) }
      : null,
  ].filter((fact): fact is { icon: typeof GraduationCapIcon; label: string } => fact !== null);

  const educationRows = buildEducationRows(profile);
  const hasWork = Boolean(profile.company || profile.position);
  const hasContact = Boolean(
    profile.email ||
      profile.whatsappPhone ||
      profile.facebookUrl ||
      profile.linkedInUrl ||
      profile.websiteUrl,
  );

  return (
    <div className="mx-auto max-w-3xl px-4 py-10 sm:px-6">
      {viewer?.isVerified ? (
        <Button variant="ghost" size="sm" asChild className="mb-6 -ml-2">
          <Link href="/directory">
            <ArrowLeftIcon />
            Back to directory
          </Link>
        </Button>
      ) : null}

      <Card>
        <CardContent className="pt-8">
          <div className="flex flex-col gap-5 sm:flex-row sm:items-start">
            <span className="relative flex size-20 shrink-0 items-center justify-center overflow-hidden rounded-full bg-muted text-lg font-medium text-muted-foreground">
              {profile.avatarUrl ? (
                <Image
                  src={profile.avatarUrl}
                  alt=""
                  fill
                  sizes="80px"
                  className="object-cover"
                />
              ) : (
                initialsOf(profile.displayName)
              )}
            </span>

            <div className="min-w-0 flex-1">
              <div className="flex flex-wrap items-start justify-between gap-3">
                <div>
                  <h1 className="text-2xl font-semibold tracking-tight">
                    {profile.displayName}
                  </h1>
                  {profile.headline ? (
                    <p className="mt-1 text-muted-foreground">{profile.headline}</p>
                  ) : null}
                </div>

                {profile.isOwnProfile ? (
                  <Button variant="outline" size="sm" asChild>
                    <Link href="/settings/profile">
                      <PencilIcon />
                      Edit
                    </Link>
                  </Button>
                ) : null}
              </div>

              {facts.length > 0 ? (
                <dl className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-sm text-muted-foreground">
                  {facts.map((fact) => (
                    <div key={fact.label} className="flex items-center gap-1.5">
                      <fact.icon className="size-4 shrink-0" />
                      <dd>{fact.label}</dd>
                    </div>
                  ))}
                </dl>
              ) : null}
            </div>
          </div>

          {profile.bio ? (
            <>
              <Separator className="my-6" />
              <div className="space-y-2">
                <h2 className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
                  About
                </h2>
                <p className="whitespace-pre-line text-sm leading-relaxed">{profile.bio}</p>
              </div>
            </>
          ) : null}

          {educationRows.length > 0 ? (
            <>
              <Separator className="my-6" />
              <div className="space-y-4">
                <h2 className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
                  Education
                </h2>
                <dl className="space-y-4">
                  {educationRows.map((row) => (
                    <div key={row.label} className="space-y-1">
                      <dt className="text-sm font-medium">{row.label}</dt>
                      <dd className="text-sm text-muted-foreground">{row.detail}</dd>
                      {row.meta ? (
                        <dd className="text-xs text-muted-foreground">{row.meta}</dd>
                      ) : null}
                    </div>
                  ))}
                </dl>
              </div>
            </>
          ) : null}

          {hasWork ? (
            <>
              <Separator className="my-6" />
              <div className="space-y-2">
                <h2 className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
                  Work
                </h2>
                <p className="text-sm">
                  {[profile.position, profile.company].filter(Boolean).join(" at ")}
                </p>
                {location ? (
                  <p className="flex items-center gap-1.5 text-sm text-muted-foreground">
                    <MapPinIcon className="size-3.5 shrink-0" />
                    {location}
                  </p>
                ) : null}
              </div>
            </>
          ) : null}

          {hasContact ? (
            <>
              <Separator className="my-6" />
              <div className="space-y-3">
                <h2 className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
                  Contact & links
                </h2>
                <div className="flex flex-wrap gap-2">
                  {profile.email ? (
                    <Button variant="outline" size="sm" asChild>
                      <a href={`mailto:${profile.email}`}>
                        <MailIcon />
                        {profile.email}
                      </a>
                    </Button>
                  ) : null}
                  {profile.whatsappPhone ? (
                    <Button variant="outline" size="sm" asChild>
                      <a
                        href={`https://wa.me/${profile.whatsappPhone.replace(/\D/g, "")}`}
                        target="_blank"
                        rel="noopener noreferrer"
                      >
                        <MessageCircleIcon />
                        WhatsApp
                      </a>
                    </Button>
                  ) : null}
                  {profile.facebookUrl ? (
                    <Button variant="outline" size="sm" asChild>
                      <a href={profile.facebookUrl} target="_blank" rel="noopener noreferrer">
                        <UsersIcon />
                        Facebook
                      </a>
                    </Button>
                  ) : null}
                  {profile.linkedInUrl ? (
                    <Button variant="outline" size="sm" asChild>
                      <a href={profile.linkedInUrl} target="_blank" rel="noopener noreferrer">
                        <LinkIcon />
                        LinkedIn
                      </a>
                    </Button>
                  ) : null}
                  {profile.websiteUrl ? (
                    <Button variant="outline" size="sm" asChild>
                      <a href={profile.websiteUrl} target="_blank" rel="noopener noreferrer">
                        <GlobeIcon />
                        Website
                      </a>
                    </Button>
                  ) : null}
                </div>
              </div>
            </>
          ) : null}

          {profile.isOwnProfile ? (
            <>
              <Separator className="my-6" />
              <Badge variant="secondary">
                Visibility: {profile.visibility.replace("_", " ").toLowerCase()}
              </Badge>
            </>
          ) : null}
        </CardContent>
      </Card>

      {!viewer ? (
        <Card className="mt-6 border-primary/25 bg-primary/5">
          <CardContent className="flex flex-wrap items-center justify-between gap-4 py-5">
            <p className="text-sm text-muted-foreground">
              Sign in as a verified alumnus to see contact details and browse the full
              directory.
            </p>
            <Button size="sm" asChild>
              <Link href="/login">Sign in</Link>
            </Button>
          </CardContent>
        </Card>
      ) : null}
    </div>
  );
}

function buildEducationRows(profile: PublicProfile) {
  const rows: Array<{ label: string; detail: string; meta?: string }> = [];

  const schoolParts = [
    profile.graduationYear ? `SSC ${profile.graduationYear}` : null,
    profile.departmentName,
  ].filter(Boolean);
  if (schoolParts.length > 0) {
    rows.push({
      label: "School",
      detail: schoolParts.join(" · "),
    });
  }

  if (
    profile.collegeName ||
    profile.collegeDepartment ||
    profile.collegeSession ||
    profile.hscPassingYear
  ) {
    const collegeDetail = [
      profile.hscPassingYear ? `HSC ${profile.hscPassingYear}` : null,
      profile.collegeName,
      profile.collegeDepartment,
    ]
      .filter(Boolean)
      .join(" · ");
    rows.push({
      label: "College",
      detail: collegeDetail,
      meta: profile.collegeSession ? `Session ${profile.collegeSession}` : undefined,
    });
  }

  if (profile.universityName || profile.universityDepartment || profile.universitySession) {
    rows.push({
      label: "University",
      detail: [profile.universityName, profile.universityDepartment].filter(Boolean).join(" · "),
      meta: profile.universitySession ? `Session ${profile.universitySession}` : undefined,
    });
  }

  if (profile.degree) {
    rows.push({
      label: "Highest degree",
      detail: profile.degree,
    });
  }

  return rows.filter((row) => row.detail.length > 0);
}
