import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import {
  ArrowLeftIcon,
  BriefcaseIcon,
  GlobeIcon,
  GraduationCapIcon,
  LinkIcon,
  MailIcon,
  MapPinIcon,
  PencilIcon,
} from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { countryName } from "@/lib/countries";
import { getProfileBySlug } from "@/lib/dal/profiles";
import { getViewer } from "@/lib/dal/session";
import { initialsOf } from "@/lib/utils";

/**
 * Next 16 passes `params` as a Promise. `PageProps` is generated by `next typegen`, but the
 * explicit shape here keeps the file readable without running codegen first.
 */
type ProfilePageProps = { params: Promise<{ slug: string }> };

export async function generateMetadata({ params }: ProfilePageProps): Promise<Metadata> {
  const { slug } = await params;
  const profile = await getProfileBySlug(slug);

  if (!profile) return { title: "Profile not found", robots: { index: false } };

  return {
    title: profile.displayName,
    description: profile.headline ?? undefined,
    // Even PUBLIC profiles stay out of search indexes; "public" here means visible to
    // signed-out visitors who have the link, not crawlable.
    robots: { index: false, follow: false },
  };
}

export default async function ProfilePage({ params }: ProfilePageProps) {
  const { slug } = await params;
  const [profile, viewer] = await Promise.all([getProfileBySlug(slug), getViewer()]);

  // The DAL returns null both for "does not exist" and "not visible to you". Presenting
  // both as 404 avoids confirming that a hidden profile exists.
  if (!profile) notFound();

  const location = [profile.city, profile.countryCode ? countryName(profile.countryCode) : null]
    .filter(Boolean)
    .join(", ");
  const role = [profile.position, profile.company].filter(Boolean).join(" at ");

  const facts = [
    profile.graduationYear
      ? { icon: GraduationCapIcon, label: `SSC ${profile.graduationYear}` }
      : null,
    profile.departmentName ? { icon: GraduationCapIcon, label: profile.departmentName } : null,
    role ? { icon: BriefcaseIcon, label: role } : null,
    location ? { icon: MapPinIcon, label: location } : null,
  ].filter((fact): fact is { icon: typeof GraduationCapIcon; label: string } => fact !== null);

  return (
    <div className="mx-auto max-w-3xl px-4 py-10 sm:px-6">
      {viewer?.isVerified ? (
        <Button variant="ghost" size="sm" asChild className="mb-6 -ml-2">
          <Link href="/directory">
            <ArrowLeftIcon />
            Back to directory
          </Link>
        </Button>
      ) : null}

      <Card>
        <CardContent className="pt-8">
          <div className="flex flex-col gap-5 sm:flex-row sm:items-start">
            <span className="relative flex size-20 shrink-0 items-center justify-center overflow-hidden rounded-full bg-muted text-lg font-medium text-muted-foreground">
              {profile.avatarUrl ? (
                <Image
                  src={profile.avatarUrl}
                  alt=""
                  fill
                  sizes="80px"
                  className="object-cover"
                />
              ) : (
                initialsOf(profile.displayName)
              )}
            </span>

            <div className="min-w-0 flex-1">
              <div className="flex flex-wrap items-start justify-between gap-3">
                <div>
                  <h1 className="text-2xl font-semibold tracking-tight">
                    {profile.displayName}
                  </h1>
                  {profile.headline ? (
                    <p className="mt-1 text-muted-foreground">{profile.headline}</p>
                  ) : null}
                </div>

                {profile.isOwnProfile ? (
                  <Button variant="outline" size="sm" asChild>
                    <Link href="/settings/profile">
                      <PencilIcon />
                      Edit
                    </Link>
                  </Button>
                ) : null}
              </div>

              {facts.length > 0 ? (
                <dl className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-sm text-muted-foreground">
                  {facts.map((fact) => (
                    <div key={fact.label} className="flex items-center gap-1.5">
                      <fact.icon className="size-4 shrink-0" />
                      <dd>{fact.label}</dd>
                    </div>
                  ))}
                </dl>
              ) : null}
            </div>
          </div>

          {profile.bio ? (
            <>
              <Separator className="my-6" />
              <p className="whitespace-pre-line text-sm leading-relaxed">{profile.bio}</p>
            </>
          ) : null}

          {profile.degree ? (
            <>
              <Separator className="my-6" />
              <div className="space-y-1">
                <h2 className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
                  Education
                </h2>
                <p className="text-sm">
                  {profile.degree}
                  {profile.departmentName ? ` · ${profile.departmentName}` : ""}
                </p>
              </div>
            </>
          ) : null}

          {profile.email || profile.linkedInUrl || profile.websiteUrl ? (
            <>
              <Separator className="my-6" />
              <div className="flex flex-wrap gap-2">
                {profile.email ? (
                  <Button variant="outline" size="sm" asChild>
                    <a href={`mailto:${profile.email}`}>
                      <MailIcon />
                      {profile.email}
                    </a>
                  </Button>
                ) : null}
                {profile.linkedInUrl ? (
                  <Button variant="outline" size="sm" asChild>
                    <a href={profile.linkedInUrl} target="_blank" rel="noopener noreferrer">
                      <LinkIcon />
                      LinkedIn
                    </a>
                  </Button>
                ) : null}
                {profile.websiteUrl ? (
                  <Button variant="outline" size="sm" asChild>
                    <a href={profile.websiteUrl} target="_blank" rel="noopener noreferrer">
                      <GlobeIcon />
                      Website
                    </a>
                  </Button>
                ) : null}
              </div>
            </>
          ) : null}

          {profile.isOwnProfile ? (
            <>
              <Separator className="my-6" />
              <Badge variant="secondary">
                Visibility: {profile.visibility.replace("_", " ").toLowerCase()}
              </Badge>
            </>
          ) : null}
        </CardContent>
      </Card>

      {!viewer ? (
        <Card className="mt-6 border-primary/25 bg-primary/5">
          <CardContent className="flex flex-wrap items-center justify-between gap-4 py-5">
            <p className="text-sm text-muted-foreground">
              Sign in as a verified alumnus to see contact details and browse the full
              directory.
            </p>
            <Button size="sm" asChild>
              <Link href="/login">Sign in</Link>
            </Button>
          </CardContent>
        </Card>
      ) : null}
    </div>
  );
}
